[toolchain]
channel = "stable"
profile = "minimal"

targets = ["thumbv7em-none-eabihf", "thumbv7m-none-eabi"]

# llvm-tools: doas pacman -S cargo-binutils
components = ["rust-src", "rustfmt", "llvm-tools"]
