[env]
PROBE_RS_CHIP = "<CHIP>"
# LOG: trace, debug, info, warn, error
DEFMT_LOG              = "trace"
DEFMT_RTT_BUFFER_SIZE  = "1024"
CARGO_REGISTRY_DEFAULT = "rsproxy"

EMBASSY_EXECUTOR_TASK_ARENA_SIZE = "8192"


[alias]
rr = "r -r"
br = "b -r"
x  = "rr --"


[build]
target = "<TARGET_TRIPLE>"
rustflags = [
    "-Clinker-plugin-lto",
    "-Clink-arg=--nmagic",
    "-Clink-arg=-Tlink.x",
    "-Clink-arg=-Tdefmt.x",
    # "-Cforce-frame-pointers",
    # "-Zmacro-backtrace",
]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# linker = "rust-lld"
runner = [
    "probe-rs",
    "run",
    "--preverify",
    "--no-location",
    # "--verify",
    # "--connect-under-reset",
    # "--log-format", "{L} {s}",
]
